# Generated by Django 5.0.4 on 2024-05-01 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu_app", "0002_alter_course_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                related_name="enrolled_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
