# Generated by Django 5.0.4 on 2024-05-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu_app", "0003_alter_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="Classroom",
        ),
        migrations.AddField(
            model_name="student",
            name="classrooms",
            field=models.ManyToManyField(to="edu_app.classroom"),
        ),
    ]
